[project]
org-name = "ballerina"
version = "1.0.1"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "xslt"
    version = "1.0.1-SNAPSHOT"
    path = "../xslt-native/build/libs/xslt-native-1.0.1-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["xslt"]

    [[platform.libraries]]
    artifactId = "axiom-api"
    version = "1.2.22"
    path = "./lib/axiom-api-1.2.22.jar"
    groupId = "org.apache.ws.commons.axiom"
    modules = ["xslt"]

    [[platform.libraries]]
    artifactId = "axiom-impl"
    version = "1.2.22"
    path = "./lib/axiom-impl-1.2.22.jar"
    groupId = "org.apache.ws.commons.axiom"
    modules = ["xslt"]
